"""password implementation

Revision ID: 539ed3735519
Revises: c8ce060dd7e8
Create Date: 2021-11-16 01:41:36.113563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539ed3735519'
down_revision = 'c8ce060dd7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
